#!/usr/bin/env bash
# runs lints
set -e

gometalinter \
  --install --update \
  --vendor \
  --disable=gotype \
  --disable=errcheck \
  --enable=goimports \
  --enable=lll --line-length=120 \
  --enable=misspell \
  ./...
